image: gitpod/workspace-dotnet

tasks: 
  - name: Start Database
    init: |
      docker compose build
      curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.100 --install-dir /home/gitpod/dotnet
      gp sync-done docker-build
    command: |
      docker compose up database

  - name: Run Netflicks
    init: |
      dotnet restore
      dotnet build "DotNetFlicks.Web/Web.csproj"
    command: |
      gp sync-await docker-build
      gp ports await 1433
      dotnet run --project "DotNetFlicks.Web/Web.csproj"

ports: 
  - name: Netflicks
    port: 5000
    onOpen: open-preview
  - name: MsSQL Database
    port: 1433
    onOpen: ignore

vscode:
  extensions:
    - amvanbaren.runme
    - muhammad-sammy.csharp
