image: gitpod/workspace-dotnet

tasks: 
  - name: Start Database
    init: |
      docker compose build 
      gp sync-done docker-build
    command: |
      docker compose up database
  - name: Build and Run Netflicks
    init: |
      curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.100 --install-dir /home/gitpod/dotnet
      dotnet build "DotNetFlicks.Web/Web.csproj"
      gp sync-await docker-build
    command: |
      gp ports await 1443
      dotnet run --project "DotNetFlicks.Web/Web.csproj"

ports: 
  - name: Netflicks
    port: 5000
    onOpen: open-preview
  - name: MsSQL Database
    port: 1443
    onOpen: ignore

vscode:
  extensions:
    - muhammad-sammy.csharp
