image:
  file: .gitpod.Dockerfile

tasks: 
  - name: Start Database
    # before: curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 6.0.100 --install-dir /home/gitpod/dotnet
    init: |
      docker compose pull database
      docker compose build
    command: |
      docker compose up database

  - name: Run Netflicks
    before: |
      curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --install-dir /home/gitpod/dotnet
      export PATH=/home/gitpod/dotnet:$PATH 
      echo "export PATH=/home/gitpod/dotnet:$PATH" >> $HOME/.bashrc
      sudo ln -s /home/gitpod/dotnet/dotnet /usr/local/bin/dotnet 
    init: |
      export PATH=/home/gitpod/dotnet:$PATH
      dotnet restore
      dotnet build "DotNetFlicks.Web/Web.csproj"
      npm install -D @playwright/test
      npx playwright install
    command: |
      export PATH=/home/gitpod/dotnet:$PATH 
      gp ports await 1433
      open README.md
      dotnet run --project "DotNetFlicks.Web/Web.csproj"

ports: 
  - name: Netflicks
    port: 5000
    onOpen: open-preview
  - name: MsSQL Database
    port: 1433
    onOpen: ignore

vscode:
  extensions:
    - amvanbaren.runme
    - muhammad-sammy.csharp
