name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v4
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with: 
          push: false
          load: true
          tags: netflicks:docker-test
  
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - 
        run: |
          echo Testing now
      -
        name: Checkout branch
        uses: actions/checkout@v4
      -
        name: Run docker-compose tests
        run: | 
          docker-compose -f docker-compose.yml up -d 
      - 
        name: Setup Node
        uses: actions/setup-node@v3
      - 
        name: Install dependencies
        run: npm ci
      - 
        name: Install playwright browsers
        run: npx playwright install-deps chromium
      - 
        name: Run tests
        run: npx playwright test

            

        # name: Run Docker images
        # run: |
        #   docker run --rm -d -p 1433:1433 --name database -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=reallyStrongPwd123' mcr.microsoft.com/azure-sql-edge
        #   docker run --rm -p 8080:8080 -e 'ConnectionStrings__DotNetFlicksConnection=Server=tcp:0.0.0.0,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;' netflicks:docker-test
  
        


  merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs: 
      - build
      - test

    steps:
      - run: |
          echo The PR was merged

      