name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with: 
          push: false
          load: true
          tags: netflicks:docker-test
      -
        name: Run Docker images
        run: |
          docker run --rm -d -p 1433:1433 --name database -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=reallyStrongPwd123' mcr.microsoft.com/azure-sql-edge
          docker run --rm -p 8080:8080 netflicks:docker-test
      
            